<?php
/**
 *
 * @copyright 2008 - https://www.clicshopping.org
 * @Brand : ClicShoppingAI(TM) at Inpi all right Reserved
 * @Licence GPL 2 & MIT
 * @Info : https://www.clicshopping.org/forum/trademark/
 *
 */

namespace ClicShopping\AI\Agents\Planning;


use ClicShopping\OM\CLICSHOPPING;
use ClicShopping\OM\Registry;
use ClicShopping\AI\Config\DomainConfig;

/**
 * TaskPlannerPrompts Class
 *
 * Centralized prompt management for TaskPlanner to ensure valid JSON outputs
 * and structured responses.
 *
 * Responsibilities:
 * - Define rigid system prompts for TaskPlanner
 * - Validate JSON schemas
 * - Provide templates for each operation type
 * - Ensure consistency of output formats
 */

class TaskPlannerPrompts
{
  /**
   * Allowed step types in plans
   */
  private const ALLOWED_STEP_TYPES = [
    'semantic_search',
    'analytics_query',
    'calculation',
    'validation_check',
    'sql_correction',
    'data_synthesis',
    'web_search',
    'filtering',
    'aggregation',
    'comparison',
  ];

  /**
   * Allowed complexity levels
   */
  private const COMPLEXITY_LEVELS = [
    'simple',
    'medium',
    'complex',
    'very_complex',
  ];

  /**
   * Get system prompt for TaskPlanner
   *
   * @return string Rigid system prompt
   */
  public static function getTaskPlannerSystemPrompt(): string
  {
    $CLICSHOPPING_Language = Registry::get('Language');
    $allowedTypes = implode(', ', self::ALLOWED_STEP_TYPES);
    $complexityLevels = implode('|', self::COMPLEXITY_LEVELS);
    $entityGuidelines = self::getEntityMetadataGuidelines();

    // Load SYSTEM prompt in English for better LLM evaluation (internal process)
    // Note: This evaluates response quality, not user-facing
    DomainConfig::loadLanguageFile('rag_task_planner');

    $array = [
      'allowed_types' => $allowedTypes,
      'complexity_levels' => $complexityLevels,
      'entity_guidelines' => $entityGuidelines
    ];

    $text_instructions_task_planner = $CLICSHOPPING_Language->getDef('text_instructions_task_planner', $array);

    return $text_instructions_task_planner;
  }

  /**
   * Build context prompt for TaskPlanner
   *
   * @param string $userQuery User query
   * @param array $memoryContext Conversation memory context
   * @param array $reasoningSteps Reasoning steps (if available)
   * @param array $metadata Additional metadata
   * @return string Complete context prompt
   */
  public static function buildTaskPlannerContext( string $userQuery, array $memoryContext = [], array $reasoningSteps = [], array $metadata = []): string
  {
    $parts = [];

    $parts[] = "--- PLANNING CONTEXT ---";
    $parts[] = "";
    $parts[] = "User Query: \"{$userQuery}\"";
    $parts[] = "";

    // NEW: Add entity metadata if available
    if (!empty($metadata['entity_type'])) {
      $parts[] = "Primary Entity Type: {$metadata['entity_type']}";
      if (!empty($metadata['entity_id'])) {
        $parts[] = "Primary Entity ID: {$metadata['entity_id']}";
      } else {
        $parts[] = "Primary Entity ID: (not specified or ambiguous)";
      }
      $parts[] = "";
    }

    // Memory context
    if (!empty($memoryContext)) {
      $parts[] = "Memory Context (last 3 interactions):";
      foreach (array_slice($memoryContext, -3) as $i => $interaction) {
        $parts[] = ((int)$i + 1) . ". User: " . substr($interaction['user_message'] ?? '', 0, 100);
        $parts[] = "   Assistant: " . substr($interaction['system_response'] ?? '', 0, 100);
        // Add entity_type if available in memory
        if (!empty($interaction['entity_type'])) {
          $parts[] = "   Entity Type: {$interaction['entity_type']}";
        }
      }
      $parts[] = "";
    }

    // Reasoning steps
    if (!empty($reasoningSteps)) {
      $parts[] = "Reasoning Required (from ReasoningAgent):";
      foreach ($reasoningSteps as $i => $step) {
        $parts[] = ((int)$i + 1) . ". " . ($step['description'] ?? $step);
      }
      $parts[] = "";
    }

    // Additional metadata
    if (!empty($metadata)) {
      $parts[] = "Additional Context:";
      foreach ($metadata as $key => $value) {
        if (is_string($value) && !in_array($key, ['entity_type', 'entity_id'])) {
          $parts[] = "- {$key}: {$value}";
        }
      }
      $parts[] = "";
    }

    $parts[] = "--- INSTRUCTIONS ---";
    $parts[] = "Generate a JSON execution plan following the schema defined in the system prompt.";
    $parts[] = "Remember: Output ONLY valid JSON, no other text.";

    return implode("\n", $parts);
  }

  /**
   * Validate JSON plan generated by LLM
   *
   * @param string $jsonString JSON to validate
   * @return array Validation result with 'valid', 'data', and 'errors' keys
   */
  public static function validatePlanJSON(string $jsonString): array
  {
    $result = [
      'valid' => false,
      'data' => null,
      'errors' => [],
    ];

    // 1. Parse JSON
    $json = json_decode($jsonString, true);

    if (json_last_error() !== JSON_ERROR_NONE) {
      $result['errors'][] = 'Invalid JSON: ' . json_last_error_msg();
      return $result;
    }

    // 2. Check required fields
    $requiredFields = ['plan_id', 'description', 'complexity', 'initial_query', 'steps'];

    foreach ($requiredFields as $field) {
      if (!isset($json[$field])) {
        $result['errors'][] = "Missing required field: {$field}";
      }
    }

    // 3. Validate complexity
    if (isset($json['complexity']) && !in_array($json['complexity'], self::COMPLEXITY_LEVELS)) {
      $result['errors'][] = "Invalid complexity level: {$json['complexity']}";
    }

    // 4. Validate steps
    if (isset($json['steps'])) {
      if (!is_array($json['steps']) || empty($json['steps'])) {
        $result['errors'][] = "Steps must be a non-empty array";
      } else {
        $stepIds = [];
        $hasFinalStep = false;

        foreach ($json['steps'] as $i => $step) {
          $stepErrors = self::validateStep($step, $i, $stepIds);
          $result['errors'] = array_merge($result['errors'], $stepErrors);

          if (isset($step['id'])) {
            $stepIds[] = $step['id'];
          }

          if (isset($step['metadata']['is_final']) && $step['metadata']['is_final'] === true) {
            $hasFinalStep = true;
          }
        }

        if (!$hasFinalStep) {
          $result['errors'][] = "At least one step must have 'is_final' set to true";
        }
      }
    }

    // 5. Final result
    if (empty($result['errors'])) {
      $result['valid'] = true;
      $result['data'] = $json;
    }

    return $result;
  }

  /**
   * Validate individual step
   *
   * @param array $step Step to validate
   * @param int $index Step index
   * @param array $existingIds Already used IDs
   * @return array Array of found errors
   */
  private static function validateStep(array $step, int $index, array $existingIds): array
  {
    $errors = [];

    // Required fields
    $requiredFields = ['id', 'type', 'description', 'prompt_content', 'depends_on', 'metadata'];

    foreach ($requiredFields as $field) {
      if (!isset($step[$field])) {
        $errors[] = "Step {$index}: Missing required field '{$field}'";
      }
    }

    // Validate type
    if (isset($step['type']) && !in_array($step['type'], self::ALLOWED_STEP_TYPES)) {
      $errors[] = "Step {$index}: Invalid type '{$step['type']}'";
    }

    // Validate unique ID
    if (isset($step['id'])) {
      if (in_array($step['id'], $existingIds)) {
        $errors[] = "Step {$index}: Duplicate ID '{$step['id']}'";
      }

      if (!preg_match('/^step_\d+$/', $step['id'])) {
        $errors[] = "Step {$index}: ID must match pattern 'step_N'";
      }
    }

    // Validate depends_on
    if (isset($step['depends_on'])) {
      if (!is_array($step['depends_on'])) {
        $errors[] = "Step {$index}: 'depends_on' must be an array";
      } else {
        foreach ($step['depends_on'] as $depId) {
          if (!in_array($depId, $existingIds)) {
            $errors[] = "Step {$index}: Dependency '{$depId}' references non-existent step";
          }
        }
      }
    }

    // Validate metadata
    if (isset($step['metadata']) && !is_array($step['metadata'])) {
      $errors[] = "Step {$index}: 'metadata' must be an object";
    }

    return $errors;
  }

  /**
   * Clean LLM response to extract JSON
   *
   * @param string $response Raw LLM response
   * @return string Cleaned JSON string
   */
  public static function cleanJSONResponse(string $response): string
  {
    // Remove markdown tags
    $cleaned = preg_replace('/```json\s*|\s*```/', '', $response);

    // Remove text before first {
    if (($pos = strpos($cleaned, '{')) !== false) {
      $cleaned = substr($cleaned, $pos);
    } else {
      // No { found, return valid empty JSON
      return '{"error": "No JSON structure found"}';
    }

    if (($pos = strrpos($cleaned, '}')) !== false) {
      $cleaned = substr($cleaned, 0, $pos + 1);
    } else {
      // No } found, add closing brace
      $cleaned .= '}';
    }

    // Trim
    $cleaned = trim($cleaned);

    if (empty($cleaned)) {
      return '{"error": "Empty JSON response"}';
    }

    $openBraces = substr_count($cleaned, '{');
    $closeBraces = substr_count($cleaned, '}');
    
    if ($openBraces > $closeBraces) {
      $cleaned .= str_repeat('}', $openBraces - $closeBraces);
    }

    if (json_last_error() !== JSON_ERROR_NONE) {
      error_log("JSON cleaning warning: " . json_last_error_msg() . " for: " . substr($cleaned, 0, 100));
      // Return valid error JSON
      return '{"error": "Invalid JSON structure", "original_error": "' . addslashes(json_last_error_msg()) . '"}';
    }

    return $cleaned;
  }

  /**
   * Returns guidelines on entity_id and entity_type management
   * To include in all system prompts related to data
   *
   * @return string Formatted guidelines
   */
  public static function getEntityMetadataGuidelines(): string
  {
    $CLICSHOPPING_Language = Registry::get('Language');
    
    // Load language file in English for internal processing
    DomainConfig::loadLanguageFile('rag_prompt_system');
    
    return $CLICSHOPPING_Language->getDef('text_rag_entity_metadata_guidelines');
  }
}