<?php
/**
 *
 * @copyright 2008 - https://www.clicshopping.org
 * @Brand : ClicShoppingAI(TM) at Inpi all right Reserved
 * @Licence GPL 2 & MIT
 * @Info : https://www.clicshopping.org/forum/trademark/
 *
 * Usage in template:
 * <?php echo $CLICSHOPPING_Hooks->output('Orders', 'PageContentTab1', null, 'display'); ?>
 * 
 * Requirements: 3.1, 3.3
 * 
 * This hook ONLY reads pre-generated insights from database.
 * Insights are generated by the Shop/Orders/Process hook when order is created.
 * If no insights exist, displays message with "Generate" button.
 */

namespace ClicShopping\Apps\AI\Ecommerce\Module\Hooks\ClicShoppingAdmin\Orders;

use ClicShopping\Apps\Configuration\ChatGpt\Classes\ClicShoppingAdmin\Gpt;
use ClicShopping\OM\Registry;
use ClicShopping\OM\HTML;
use ClicShopping\Apps\AI\Ecommerce\Ecommerce as EcommerceApp;
use ClicShopping\Sites\Common\HTMLOverrideCommon;

/**
 * PageContentTab1 Hook
 * 
 * Displays order insights as HTML in the admin interface.
 * READS ONLY from database - no LLM calls here.
 */
 
class PageContentTab1 implements \ClicShopping\OM\Modules\HooksInterface
{
  public mixed $app;
  private bool $debug = false;
  
  public function __construct()
  {
    if (!Registry::exists('Ecommerce')) {
      Registry::set('Ecommerce', new EcommerceApp());
    }
    
    $this->app = Registry::get('Ecommerce');
    
    $this->app->loadDefinitions('Module/Hooks/ClicShoppingAdmin/Orders/page_content_tab_1');
    
    if (defined('CLICSHOPPING_APP_ECOMMERCE_EC_DEBUG') && CLICSHOPPING_APP_ECOMMERCE_EC_DEBUG === 'True') {
      $this->debug = true;
    }
  }

  /**
   * Display method - Returns HTML output
   * 
   * Reads pre-generated insights from database (generated by Shop hook after order creation)
   * NO LLM CALLS - only database reads
   * 
   * @return string HTML output for display
   */
  public function display(): string
  {
    $requiredConstants = [
      'CLICSHOPPING_APP_ECOMMERCE_EC_STATUS',
      'CLICSHOPPING_APP_CHATGPT_RA_OPENAI_EMBEDDING',
      'CLICSHOPPING_APP_CHATGPT_RA_STATUS',
    ];

    foreach ($requiredConstants as $const) {
      if (!\defined($const) || \constant($const) !== 'True') {
        return false;
      }
    }

    if (!Gpt::checkGptStatus()) {
      return false;
    }

    // Get order ID from URL parameter
    if (!isset($_GET['oID'])) {
      return '';
    }
    
    $orderId = (int)HTML::sanitize($_GET['oID']);
    
    if ($orderId <= 0) {
      return '';
    }
    
    try {
      // Get insight type from parameter or default to 'summary'
      $insightType = isset($_GET['insight_type']) ? HTML::sanitize($_GET['insight_type']) : 'summary';
      
      // Load insights from database ONLY (no on-demand generation)
      $insights = $this->loadInsightsFromDatabase($orderId, $insightType);
      
      if (!$insights) {
        // No insights found - show message with regenerate button
        if ($this->debug) {
          error_log("[WARN] [PageContentTab1] No stored insights found for order #{$orderId}");
        }
        
        return $this->renderNoInsights($orderId, $insightType);
      }
      
      // Format as HTML with regenerate button
      $htmlContent = $this->formatInsightsAsHtml($insights, $insightType, $orderId);
      
      // Escape HTML for JavaScript injection
      $escapedContent = HTMLOverrideCommon::escapeForJs($htmlContent);
      
      // Create a new tab (Tab4) for insights
      $tabTitle = $this->app->getDef('tab_insights');
      $escapedTabTitle = HTMLOverrideCommon::escapeForJs($tabTitle);
      
      // Wrap in JavaScript to create new tab
      $output = <<<EOD
<!-- ######################## -->
<!--  Start Order Insights Tab4   -->
<!-- ######################## -->
<script>
$(document).ready(function() {
  $('#myTab').append('<li class="nav-item"><a href="#tab4" role="tab" data-bs-toggle="tab" class="nav-link">{$escapedTabTitle}</a></li>');
  $('.tab-content').append('<div class="tab-pane" id="tab4">{$escapedContent}</div>');
});
</script>
<!-- ######################## -->
<!--  End Order Insights Tab4     -->
<!-- ######################## -->
EOD;
      
      return $output;
      
    } catch (\Exception $e) {
      error_log("[ERROR] [PageContentTab1] Error: " . $e->getMessage());
      return $this->renderError($e->getMessage());
    }
  }
  
  /**
   * Load insights from database
   * 
   * @param int $orderId Order ID
   * @param string $insightType Type of insight
   * @return array|null Insights array or null if not found
   */
  private function loadInsightsFromDatabase(int $orderId, string $insightType): ?array
  {
    $ClicShopping_Db = Registry::get('Db');
    
    $query = $ClicShopping_Db->prepare('
      SELECT * 
      FROM :table_rag_agent_order_insights 
      WHERE orders_id = :orders_id 
      AND insight_type = :insight_type
      ORDER BY generated_at DESC
      LIMIT 1
    ');
    $query->bindInt(':orders_id', $orderId);
    $query->bindValue(':insight_type', $insightType);
    $query->execute();
    
    $row = $query->fetch();
    
    if (!$row) {
      return null;
    }
    
    // Convert stored data back to array format
    return [
      'success' => true,
      'insight_type' => $row['insight_type'],
      'insights' => json_decode($row['insights'], true) ?? [],
      'confidence' => (float)$row['confidence'],
      'recommendations' => json_decode($row['recommendations'], true) ?? [],
      'summary' => $row['summary'] ?? '',
      'generated_at' => $row['generated_at'],
      'execution_time_ms' => (float)$row['execution_time_ms']
    ];
  }
  
  /**
   * Render "no insights" message with regenerate button
   * 
   * @param int $orderId Order ID
   * @param string $insightType Type of insight
   * @return string HTML output
   */
  private function renderNoInsights(int $orderId, string $insightType): string
  {
    $CLICSHOPPING_Orders = Registry::get('Orders');
    
    $html = '<div class="card mt-3">';
    $html .= '<div class="card-header bg-warning text-dark">';
    $html .= '<h5 class="mb-0"><i class="bi bi-exclamation-triangle"></i> ' . $this->app->getDef('text_no_insights') . '</h5>';
    $html .= '</div>';
    $html .= '<div class="card-body">';
    $html .= '<div class="alert alert-info">';
    $html .= '<p><strong>' . $this->app->getDef('text_insights_not_generated') . '</strong></p>';
    $html .= '<p>' . $this->app->getDef('text_insights_explanation') . '</p>';
    $html .= '</div>';
    
    // Regenerate button
    $regenerateUrl = $CLICSHOPPING_Orders->link('Orders&RegenerateInsights&oID=' . $orderId . '&insight_type=' . $insightType);
    $html .= '<div class="text-center mt-3">';
    $html .= HTML::button($this->app->getDef('button_generate_insights'), null, $regenerateUrl, 'primary');
    $html .= '</div>';
    
    $html .= '<div class="mt-3">';
    $html .= '<small class="text-muted">' . $this->app->getDef('text_insights_note') . '</small>';
    $html .= '</div>';
    
    $html .= '</div>';
    $html .= '</div>';
    
    // Escape for JavaScript
    $escapedContent = HTMLOverrideCommon::escapeForJs($html);
    $tabTitle = $this->app->getDef('tab_insights');
    $escapedTabTitle = HTMLOverrideCommon::escapeForJs($tabTitle);
    
    // Create Tab4 with "no insights" message
    $output = <<<EOD
<!-- ######################## -->
<!--  Start Order Insights Tab4 (No Data)  -->
<!-- ######################## -->
<script>
$(document).ready(function() {
  $('#myTab').append('<li class="nav-item"><a href="#tab4" role="tab" data-bs-toggle="tab" class="nav-link">{$escapedTabTitle}</a></li>');
  $('.tab-content').append('<div class="tab-pane" id="tab4">{$escapedContent}</div>');
});
</script>
<!-- ######################## -->
<!--  End Order Insights Tab4 (No Data)    -->
<!-- ######################## -->
EOD;
    
    return $output;
  }
  
  /**
   * Format insights as HTML with regenerate button
   * 
   * @param array $insights Insights data
   * @param string $insightType Type of insight
   * @param int $orderId Order ID
   * @return string HTML content
   */
  private function formatInsightsAsHtml(array $insights, string $insightType, int $orderId): string
  {
    $CLICSHOPPING_Orders = Registry::get('Orders');
    
    // Regenerate button URL
    $regenerateUrl = $CLICSHOPPING_Orders->link('Orders&RegenerateInsights&oID=' . $orderId . '&insight_type=' . $insightType);

    $html = '<div class="col-md-12">';
    $html .= '<div class="mainTitle">';
    $html .= '<div class="row">';
    $html .= '<div class="col-md-10">';
    $html .= $this->app->getDef('text_order_insights') . ' - ' . ucfirst($insightType);
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</div>';

    // Summary
    if (!empty($insights['summary'])) {
      $html .= '<div class="alert alert-light">';
      $html .= '<strong>' . $this->app->getDef('text_summary') . ':</strong> ' . htmlspecialchars($insights['summary']);
      $html .= '</div>';
    }
    
    // Confidence
    if (isset($insights['confidence'])) {
      $confidencePercent = round($insights['confidence'] * 100);
      $confidenceClass = $confidencePercent >= 80 ? 'success' : ($confidencePercent >= 60 ? 'warning' : 'danger');
      $html .= '<div class="mb-3">';
      $html .= '<span class="badge bg-' . $confidenceClass . '">' . $this->app->getDef('text_confidence') . ': ' . $confidencePercent . '%</span>';
      if (isset($insights['execution_time_ms'])) {
        $html .= ' <span class="badge bg-secondary">' . round($insights['execution_time_ms']) . 'ms</span>';
      }
      $html .= '</div>';
    }
    
    // Insights
    if (!empty($insights['insights'])) {
      $html .= '<h6><i class="bi bi-info-circle"></i> ' . $this->app->getDef('text_key_insights') . ':</h6>';
      $html .= '<ul class="list-group mb-3">';
      foreach ($insights['insights'] as $insight) {
        $html .= '<li class="list-group-item">' . htmlspecialchars($insight) . '</li>';
      }
      $html .= '</ul>';
    }
    
    // Recommendations
    if (!empty($insights['recommendations'])) {
      $html .= '<h6><i class="bi bi-arrow-right-circle"></i> ' . $this->app->getDef('text_recommendations') . ':</h6>';
      $html .= '<ul class="list-group">';
      foreach ($insights['recommendations'] as $recommendation) {
        $html .= '<li class="list-group-item list-group-item-action">' . htmlspecialchars($recommendation) . '</li>';
      }
      $html .= '</ul>';
    }
    $html .= '<div class="py-4"></div>';

    return $html;
  }
  
  /**
   * Render error message
   * 
   * @param string $message Error message
   * @return string HTML output
   */
  private function renderError(string $message): string
  {
    $html = '<div class="alert alert-danger"><i class="bi bi-x-circle"></i> ' . $this->app->getDef('text_error') . ': ' . htmlspecialchars($message) . '</div>';
    
    $escapedContent = HTMLOverrideCommon::escapeForJs($html);
    $tabTitle = $this->app->getDef('tab_insights');
    $escapedTabTitle = HTMLOverrideCommon::escapeForJs($tabTitle);
    
    $output = <<<EOD
<script>
$(document).ready(function() {
  $('#myTab').append('<li class="nav-item"><a href="#tab4" role="tab" data-bs-toggle="tab" class="nav-link">{$escapedTabTitle}</a></li>');
  $('.tab-content').append('<div class="tab-pane" id="tab4">{$escapedContent}</div>');
});
</script>
EOD;
    
    return $output;
  }
  
}
