<?php
/**
 *
 * @copyright 2008 - https://www.clicshopping.org
 * @Brand : ClicShoppingAI(TM) at Inpi all right Reserved
 * @Licence GPL 2 & MIT
 * @Info : https://www.clicshopping.org/forum/trademark/
 *
 */

namespace ClicShopping\Apps\AI\Ecommerce\Sql\MariaDb;

use ClicShopping\OM\Cache;
use ClicShopping\OM\Registry;

class MariaDb
{
  /**
   * Executes the installation process for the Ecommerce module.
   * This method loads necessary definitions and initializes the database setup.
   *
   * @return void
   */
  public function execute()
  {
    $CLICSHOPPING_Ecommerce = Registry::get('Ecommerce');
    $CLICSHOPPING_Ecommerce->loadDefinitions('Sites/ClicShoppingAdmin/install');

    self::installDbMenuAdministration();
    self::installDb();
  }

  /**
   * Installs the database entries for the administration menu related to the Page Manager module.
   *
   * This method checks if the required menu entry exists in the 'administrator_menu' table.
   * If the entry does not exist, it creates a new entry with its corresponding metadata and language-specific descriptions.
   * Once the entries are added, it clears the administrator menu cache to ensure the changes are applied.
   *
   * @return void
   */
  private static function installDbMenuAdministration(): void
  {
    $CLICSHOPPING_Db = Registry::get('Db');
    $CLICSHOPPING_Ecommerce = Registry::get('Ecommerce');
    $CLICSHOPPING_Language = Registry::get('Language');

    $Qcheck = $CLICSHOPPING_Db->get('administrator_menu', 'app_code', ['app_code' => 'app_ai_ecommerce']);

    if ($Qcheck->fetch() === false) {
      $sql_data_array = ['sort_order' => 0,
        'link' => 'index.php?A&AI\Ecommerce&Ecommerce',
        'image' => '',
        'b2b_menu' => 0,
        'access' => 0,
        'app_code' => 'app_ai_ecommerce'
      ];

      $insert_sql_data = ['parent_id' => 6];
      $sql_data_array = array_merge($sql_data_array, $insert_sql_data);

      $CLICSHOPPING_Db->save('administrator_menu', $sql_data_array);

      $id = $CLICSHOPPING_Db->lastInsertId();
      $languages = $CLICSHOPPING_Language->getLanguages();

      for ($i = 0, $n = \count($languages); $i < $n; $i++) {
        $language_id = $languages[$i]['id'];
        $sql_data_array = ['label' => $CLICSHOPPING_Ecommerce->getDef('title_menu')];

        $insert_sql_data = [
          'id' => (int)$id,
          'language_id' => (int)$language_id
        ];

        $sql_data_array = array_merge($sql_data_array, $insert_sql_data);

        $CLICSHOPPING_Db->save('administrator_menu_description', $sql_data_array);

      }

      Cache::clear('menu-administrator');
    }
  }

  /**
   * Installs the necessary database tables required for the Page Manager module if they do not already exist.
   *
   * @return void
   */
  private static function installDb()
  {
    $CLICSHOPPING_Db = Registry::get('Db');

    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_rag_agent_order_insights"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
CREATE TABLE IF NOT EXISTS :table_rag_agent_order_insights (
  insight_id int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key - unique identifier for each insight',
  orders_id int(11) NOT NULL COMMENT 'FK to orders table - order being analyzed',
  insight_type varchar(50) NOT NULL DEFAULT 'summary' COMMENT 'Type of insight - summary, recommendations, etc.',
  insights text NOT NULL COMMENT 'JSON array of key insights generated by LLM',
  confidence decimal(3,2) NOT NULL DEFAULT 0.80 COMMENT 'Confidence score of the analysis (0-1)',
  recommendations text COMMENT 'JSON array of actionable recommendations',
  summary text COMMENT 'Brief summary of the insights',
  raw_response text COMMENT 'Raw LLM response for debugging',
  execution_time_ms decimal(10,2) COMMENT 'Time taken to generate insights in milliseconds',
  generated_at datetime NOT NULL DEFAULT NOW() COMMENT 'Timestamp when insights were generated',
  language_id int(11) DEFAULT NULL COMMENT 'FK to languages table - language of the insights',
  PRIMARY KEY (insight_id),
  KEY idx_orders_id (orders_id),
  KEY idx_insight_type (insight_type),
  KEY idx_generated_at (generated_at),
  KEY idx_language_id (language_id),
  KEY idx_orders_insight_type (orders_id, insight_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores AI-generated insights for orders - summary, recommendations, and analysis'
EOD;
      $CLICSHOPPING_Db->exec($sql);
    }

    // Create embeddings table for order insights
    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_rag_agent_order_insights_embedding"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
CREATE TABLE IF NOT EXISTS :table_rag_agent_order_insights_embedding (
    id SERIAL PRIMARY KEY COMMENT 'Primary key - unique identifier for each insight embedding',
    content longtext DEFAULT NULL COMMENT 'Insight content for embedding generation - summary, recommendations, analysis',
    type TEXT DEFAULT NULL COMMENT 'Type of content - summary, recommendations, full_insights',
    sourcetype TEXT DEFAULT 'automated' COMMENT 'Source type - automated (from LLM), manual, imported',
    sourcename TEXT DEFAULT 'insights_agent' COMMENT 'Name of the source system or process',
    embedding VECTOR(3072) NOT NULL COMMENT 'Vector embedding (3072 dimensions) for semantic search',
    chunknumber INT DEFAULT 128 COMMENT 'Chunk size used for embedding generation',
    date_modified DATETIME DEFAULT NULL COMMENT 'Last modification timestamp',
    entity_id INT COMMENT 'FK to rag_agent_order_insights table - insight ID',
    metadata LONGTEXT COMMENT 'JSON metadata for the embedding',
    language_id INT DEFAULT NULL COMMENT 'Language ID from languages table',
    KEY idx_entity_id (entity_id),
    KEY idx_language_id (language_id),
    KEY idx_date_modified (date_modified)
) COMMENT='Vector embeddings for order insights - enables semantic insight search and pattern analysis across orders'
EOD;
      $CLICSHOPPING_Db->exec($sql);

      // Create vector index
      $CLICSHOPPING_Db->exec('CREATE VECTOR INDEX embedding_index ON :table_rag_agent_order_insights_embedding (embedding)');
    }

    // Create SEO SERP reports table
    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_seo_serp_reports"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
CREATE TABLE IF NOT EXISTS :table_seo_serp_reports (
  id int(11) NOT NULL AUTO_INCREMENT,
  entity_type varchar(50) NOT NULL,
  entity_id int(11) NOT NULL,
  language_id int(11) NOT NULL,
  url varchar(512) DEFAULT NULL,
  serp_source varchar(50) DEFAULT NULL,
  serp_query varchar(512) DEFAULT NULL,
  serp_data longtext DEFAULT NULL,
  seo_before longtext DEFAULT NULL,
  seo_after longtext DEFAULT NULL,
  proposed_changes longtext DEFAULT NULL,
  audit_result longtext DEFAULT NULL,
  summary text DEFAULT NULL,
  seo_score_before int(11) DEFAULT 0,
  seo_score_after int(11) DEFAULT 0,
  status varchar(50) DEFAULT NULL,
  triggered_by varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT NOW(),
  updated_at datetime NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  pipeline_metrics JSON NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_entity (entity_type, entity_id, language_id),
  KEY idx_status (status),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
EOD;
      $CLICSHOPPING_Db->exec($sql);
    }

    // Create products_seo_embedding table
    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_products_seo_embedding"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
    CREATE TABLE IF NOT EXISTS :table_products_seo_embedding (
     id              INT(11)       NOT NULL AUTO_INCREMENT COMMENT 'Primary key - unique identifier for each SEO embedding chunk',
     content         TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Text content embedded - serialized SEO report data (title, meta, H1-H3, keywords, scores)',
     type            TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type of SEO content: initial_report | optimized_report | audit_summary | suggestion',
     sourcetype      TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Trigger origin: manual | hook | cron',
     sourcename      TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Source identifier: SeoReport | AgentSeo | AgentAuditSeo | AgentSerp',
     embedding       VECTOR(3072)  NOT NULL COMMENT 'Vector embedding 3072 dimensions - OpenAI text-embedding-3-large',
     chunknumber     INT(11)       DEFAULT 128 COMMENT 'Chunk number for large reports - default 128 tokens per chunk',
     date_modified   DATETIME      DEFAULT NULL COMMENT 'Timestamp of last modification',
     entity_id       INT(11)       NOT NULL COMMENT 'FK - references the entity (category, product, cms page)',
      entity_type     VARCHAR(50)   COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity type: category | product | cms',
     language_id     INT(11)       NOT NULL COMMENT 'FK to languages table',
     metadata        LONGTEXT      COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'JSON: url, page_type, seo_score_before, seo_score_after, status, report_raw, suggestions, audit_result, serp_data',
      PRIMARY KEY (id),
      KEYidx_entity_lang    (entity_id,language_id),
      KEYidx_type           (type(50)),
      KEYidx_sourcetype     (sourcetype(50)),
      KEYidx_date_modified  (date_modified)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    EOD;
      $CLICSHOPPING_Db->exec($sql);
    }


    // Create products_seo_embedding table
    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_categories_seo_embedding"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
    CREATE TABLE IF NOT EXISTS :table_categories_seo_embedding (
      id              INT(11)       NOT NULL AUTO_INCREMENT COMMENT 'Primary key - unique identifier for each SEO embedding chunk',
      content         TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Text content embedded - serialized SEO report data (title, meta, H1-H3, keywords, scores)',
      type            TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type of SEO content: initial_report | optimized_report | audit_summary | suggestion',
      sourcetype      TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Trigger origin: manual | hook | cron',
      sourcename      TEXT          COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Source identifier: SeoReport | AgentSeo | AgentAuditSeo | AgentSerp',
      embedding       VECTOR(3072)  NOT NULL COMMENT 'Vector embedding 3072 dimensions - OpenAI text-embedding-3-large',
      chunknumber     INT(11)       DEFAULT 128 COMMENT 'Chunk number for large reports - default 128 tokens per chunk',
      date_modified   DATETIME      DEFAULT NULL COMMENT 'Timestamp of last modification',
      entity_id       INT(11)       NOT NULL COMMENT 'FK - references the entity (category, product, cms page)',
        entity_type     VARCHAR(50)   COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity type: category | product | cms',
      language_id     INT(11)       NOT NULL COMMENT 'FK to languages table',
      metadata        LONGTEXT      COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'JSON: url, page_type, seo_score_before, seo_score_after, status, report_raw, suggestions, audit_result, serp_data',
      PRIMARY KEY (id),
      KEY idx_entity_lang    (entity_id, language_id),
      KEY idx_type           (type(50)),
      KEY idx_sourcetype     (sourcetype(50)),
      KEY idx_date_modified  (date_modified)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    EOD;
      $CLICSHOPPING_Db->exec($sql);
    }
  }
}
