<?php
/**
 *
 * @copyright 2008 - https://www.clicshopping.org
 * @Brand : ClicShoppingAI(TM) at Inpi all right Reserved
 * @Licence GPL 2 & MIT
 * @Info : https://www.clicshopping.org/forum/trademark/
 *
 */

namespace ClicShopping\Apps\AI\Ecommerce\Sql\MariaDb;

use ClicShopping\OM\Cache;
use ClicShopping\OM\Registry;

class MariaDb
{
  /**
   * Executes the installation process for the Ecommerce module.
   * This method loads necessary definitions and initializes the database setup.
   *
   * @return void
   */
  public function execute()
  {
    $CLICSHOPPING_Ecommerce = Registry::get('Ecommerce');
    $CLICSHOPPING_Ecommerce->loadDefinitions('Sites/ClicShoppingAdmin/install');

    self::installDbMenuAdministration();
    self::installDb();
  }

  /**
   * Installs the database entries for the administration menu related to the Page Manager module.
   *
   * This method checks if the required menu entry exists in the 'administrator_menu' table.
   * If the entry does not exist, it creates a new entry with its corresponding metadata and language-specific descriptions.
   * Once the entries are added, it clears the administrator menu cache to ensure the changes are applied.
   *
   * @return void
   */
  private static function installDbMenuAdministration(): void
  {
    $CLICSHOPPING_Db = Registry::get('Db');
    $CLICSHOPPING_Ecommerce = Registry::get('Ecommerce');
    $CLICSHOPPING_Language = Registry::get('Language');

    $Qcheck = $CLICSHOPPING_Db->get('administrator_menu', 'app_code', ['app_code' => 'app_ai_ecommerce']);

    if ($Qcheck->fetch() === false) {
      $sql_data_array = ['sort_order' => 0,
        'link' => 'index.php?A&AI\Ecommerce&Ecommerce',
        'image' => '',
        'b2b_menu' => 0,
        'access' => 0,
        'app_code' => 'app_ai_ecommerce'
      ];

      $insert_sql_data = ['parent_id' => 6];
      $sql_data_array = array_merge($sql_data_array, $insert_sql_data);

      $CLICSHOPPING_Db->save('administrator_menu', $sql_data_array);

      $id = $CLICSHOPPING_Db->lastInsertId();
      $languages = $CLICSHOPPING_Language->getLanguages();

      for ($i = 0, $n = \count($languages); $i < $n; $i++) {
        $language_id = $languages[$i]['id'];
        $sql_data_array = ['label' => $CLICSHOPPING_Ecommerce->getDef('title_menu')];

        $insert_sql_data = [
          'id' => (int)$id,
          'language_id' => (int)$language_id
        ];

        $sql_data_array = array_merge($sql_data_array, $insert_sql_data);

        $CLICSHOPPING_Db->save('administrator_menu_description', $sql_data_array);

      }

      Cache::clear('menu-administrator');
    }
  }

  /**
   * Installs the necessary database tables required for the Page Manager module if they do not already exist.
   *
   * @return void
   */
  private static function installDb()
  {
    $CLICSHOPPING_Db = Registry::get('Db');

    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_rag_order_insights"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
CREATE TABLE IF NOT EXISTS :table_rag_order_insights (
  insight_id int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key - unique identifier for each insight',
  orders_id int(11) NOT NULL COMMENT 'FK to orders table - order being analyzed',
  insight_type varchar(50) NOT NULL DEFAULT 'summary' COMMENT 'Type of insight - summary, recommendations, etc.',
  insights text NOT NULL COMMENT 'JSON array of key insights generated by LLM',
  confidence decimal(3,2) NOT NULL DEFAULT 0.80 COMMENT 'Confidence score of the analysis (0-1)',
  recommendations text COMMENT 'JSON array of actionable recommendations',
  summary text COMMENT 'Brief summary of the insights',
  raw_response text COMMENT 'Raw LLM response for debugging',
  execution_time_ms decimal(10,2) COMMENT 'Time taken to generate insights in milliseconds',
  generated_at datetime NOT NULL DEFAULT NOW() COMMENT 'Timestamp when insights were generated',
  language_id int(11) DEFAULT NULL COMMENT 'FK to languages table - language of the insights',
  PRIMARY KEY (insight_id),
  KEY idx_orders_id (orders_id),
  KEY idx_insight_type (insight_type),
  KEY idx_generated_at (generated_at),
  KEY idx_language_id (language_id),
  KEY idx_orders_insight_type (orders_id, insight_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores AI-generated insights for orders - summary, recommendations, and analysis'
EOD;
      $CLICSHOPPING_Db->exec($sql);
    }

    // Create embeddings table for order insights
    $Qcheck = $CLICSHOPPING_Db->query('show tables like ":table_rag_order_insights_embedding"');

    if ($Qcheck->fetch() === false) {
      $sql = <<<EOD
CREATE TABLE IF NOT EXISTS :table_rag_order_insights_embedding (
    id SERIAL PRIMARY KEY COMMENT 'Primary key - unique identifier for each insight embedding',
    content longtext DEFAULT NULL COMMENT 'Insight content for embedding generation - summary, recommendations, analysis',
    type TEXT DEFAULT NULL COMMENT 'Type of content - summary, recommendations, full_insights',
    sourcetype TEXT DEFAULT 'automated' COMMENT 'Source type - automated (from LLM), manual, imported',
    sourcename TEXT DEFAULT 'insights_agent' COMMENT 'Name of the source system or process',
    embedding VECTOR(3072) NOT NULL COMMENT 'Vector embedding (3072 dimensions) for semantic search',
    chunknumber INT DEFAULT 128 COMMENT 'Chunk size used for embedding generation',
    date_modified DATETIME DEFAULT NULL COMMENT 'Last modification timestamp',
    entity_id INT COMMENT 'FK to rag_order_insights table - insight ID',
    metadata LONGTEXT COMMENT 'JSON metadata for the embedding',
    language_id INT DEFAULT NULL COMMENT 'Language ID from languages table',
    KEY idx_entity_id (entity_id),
    KEY idx_language_id (language_id),
    KEY idx_date_modified (date_modified)
) COMMENT='Vector embeddings for order insights - enables semantic insight search and pattern analysis across orders'
EOD;
      $CLICSHOPPING_Db->exec($sql);

      // Create vector index
      $CLICSHOPPING_Db->exec('CREATE VECTOR INDEX embedding_index ON :table_rag_order_insights_embedding (embedding)');
    }
  }
}